version: "3.7"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  amzn-linux-2:
    depends_on:
      - db
    build: .
    image: httpd-php-fpm-wordpress-docker-amzn-linux-2:0.1
    container_name: amzn-linux-2
    privileged: true
    restart: always
    ports:
      - "8980:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./conf_files/www.conf:/etc/php-fpm.d/www.conf
      - ./html:/var/www/html
      - type: bind
        source: ./log/httpd
        target: /var/log/httpd
      - type: bind
        source: ./share
        target: /share
      - type: bind
        source: ~/.aws
        target: /home/ec2-user/.aws
